import React from "react";
import PostCard from "../components/blog/PostCard";
import { Row } from "../components/layout/Layout.elements";
import Navbar from "../components/navbar/Navbar";

const blog = () => {
  const demopost = [
    {
      _id: "613e49756b8d2300155e9d63",
      title: "¿Cuáles son las mejores horas para publicar en redes?",
      slug: "cuales-son-las-mejores-horas-para-publicar-en-redes",
      description:
        "Cuando posteas ignorando los horarios en que tus seguidores están activos en redes estas malgastando esfuerzos. Aunque tus contenidos sean los mejores. Si los publicas cuando no hay nadie viendo se esfumarán y pasarán desapercibidos. ",
      published_at: "2021-09-12T18:42:16.864Z",
      postData: [
        {
          __component: "post.image",
          _id: "613e49756b8d2300155e9d64",
          imageDescription: "Redes sociales. Fuente: Pexels",
          __v: 0,
          image: {
            _id: "613e48386b8d2300155e9d62",
            name: "SocialNetworks.webp",
            alternativeText: "",
            caption: "",
            hash: "Social_Networks_943d5041ae",
            ext: ".webp",
            mime: "image/webp",
            size: 41.53,
            width: 1920,
            height: 1080,
            url: "https://infutblog.s3.us-east-2.amazonaws.com/Social_Networks_943d5041ae.webp",
            formats: {
              thumbnail: {
                name: "thumbnail_SocialNetworks.webp",
                hash: "thumbnail_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 245,
                height: 138,
                size: 3.92,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/thumbnail_Social_Networks_943d5041ae.webp",
              },
              large: {
                name: "large_SocialNetworks.webp",
                hash: "large_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 1000,
                height: 563,
                size: 21.1,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/large_Social_Networks_943d5041ae.webp",
              },
              medium: {
                name: "medium_SocialNetworks.webp",
                hash: "medium_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 750,
                height: 422,
                size: 15.42,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/medium_Social_Networks_943d5041ae.webp",
              },
              small: {
                name: "small_SocialNetworks.webp",
                hash: "small_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 500,
                height: 281,
                size: 9.56,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/small_Social_Networks_943d5041ae.webp",
              },
            },
            provider: "aws-s3",
            related: ["613e49756b8d2300155e9d64"],
            createdAt: "2021-09-12T18:34:32.410Z",
            updatedAt: "2021-09-12T18:39:49.489Z",
            __v: 0,
            id: "613e48386b8d2300155e9d62",
          },
          id: "613e49756b8d2300155e9d64",
        },
        {
          __component: "post.paragraph",
          _id: "613e49756b8d2300155e9d65",
          text: "¿Te ha pasado que has publicado algo en tus redes sociales y no tienes un buen engagement?. Quizá has pasado bastante tiempo pensando en el contenido, pero cuando los publicas no consigues ni siquiera un like. ¿Qué está pasando? ¿Como puedes hacer para que tus contenidos atraigan a tu público?\n\nPuede que se te haya olvidado un factor importantísimo a la hora de planear tu estrategia de redes sociales: tener en cuenta los mejores horarios para publicar. ¿No lo habías pensado? Pues bien, a continuación, te vamos a contar como puedes conocer el mejor momento para postear en redes sociales.\n\nCuando posteas ignorando los horarios en que tus seguidores están activos en redes estas malgastando esfuerzos. Aunque tus contenidos sean los mejores. Si los publicas cuando no hay nadie viendo se esfumarán y pasarán desapercibidos. \n\nEso sí, ten en cuenta que no existe una “mejor hora” como tal, ya que el horario va a depender de múltiples factores. \n\n1. La red social en la que publicas: \n\n    No es lo mismo publicar para Twitter que para Instagram. Son redes sociales totalmente diferentes y por ende, tendrán sus propias frecuencias de publicación y esto es algo muy importante a   tener en cuenta. \n\n2.\tTu público objetivo:\n\n    Es fundamental conocer a las personas a las que nos dirigimos. Pero no solo conocer cuando están más activos en redes sociales, sino que también es muy importante saber el tipo de contenido que consumen. Para esto viene bien las herramientas de analítica y medición.\n\n3.\tEl sector de tu negocio:\n\n    El mejor momento para publicar no es el mismo para un restaurante que para una discoteca. Los momentos de actividad cambian y es algo que también hay que considerar.\n\nEntonces ¿Cómo puedes saber cuál es la mejor hora para publicar? \n\nPara ello puedes dejarte llevar por lo que indican diversos estudios, o bien puedes descubrir por ti mismo el momento optimo en que tus seguidores están mas activos y así optimizar tus contenidos.\n\nSi decides optar por la primera opción aquí te dejamos las mejores horas para publicar en redes sociales de acuerdo a los estudios.\n\n### to do\n\nSi quieres descubrir por ti mismo los horarios de actividad de tus seguidores, acá te mostramos algunas herramientas que te ayudaran a saber el mejor horario para publicar.  \n\n### to do\n\n",
          __v: 0,
          id: "613e49756b8d2300155e9d65",
        },
      ],
      createdAt: "2021-09-12T18:39:49.433Z",
      updatedAt: "2021-09-12T18:42:16.934Z",
      __v: 1,
      id: "613e49756b8d2300155e9d63",
    },
    {
      _id: "613e49756b8d2300155e9d63",
      title: "¿Cuáles son las mejores horas para publicar en redes?",
      slug: "cuales-son-las-mejores-horas-para-publicar-en-redes",
      description:
        "Cuando posteas ignorando los horarios en que tus seguidores están activos en redes estas malgastando esfuerzos. Aunque tus contenidos sean los mejores. Si los publicas cuando no hay nadie viendo se esfumarán y pasarán desapercibidos. ",
      published_at: "2021-09-12T18:42:16.864Z",
      postData: [
        {
          __component: "post.image",
          _id: "613e49756b8d2300155e9d64",
          imageDescription: "Redes sociales. Fuente: Pexels",
          __v: 0,
          image: {
            _id: "613e48386b8d2300155e9d62",
            name: "SocialNetworks.webp",
            alternativeText: "",
            caption: "",
            hash: "Social_Networks_943d5041ae",
            ext: ".webp",
            mime: "image/webp",
            size: 41.53,
            width: 1920,
            height: 1080,
            url: "https://infutblog.s3.us-east-2.amazonaws.com/Social_Networks_943d5041ae.webp",
            formats: {
              thumbnail: {
                name: "thumbnail_SocialNetworks.webp",
                hash: "thumbnail_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 245,
                height: 138,
                size: 3.92,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/thumbnail_Social_Networks_943d5041ae.webp",
              },
              large: {
                name: "large_SocialNetworks.webp",
                hash: "large_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 1000,
                height: 563,
                size: 21.1,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/large_Social_Networks_943d5041ae.webp",
              },
              medium: {
                name: "medium_SocialNetworks.webp",
                hash: "medium_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 750,
                height: 422,
                size: 15.42,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/medium_Social_Networks_943d5041ae.webp",
              },
              small: {
                name: "small_SocialNetworks.webp",
                hash: "small_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 500,
                height: 281,
                size: 9.56,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/small_Social_Networks_943d5041ae.webp",
              },
            },
            provider: "aws-s3",
            related: ["613e49756b8d2300155e9d64"],
            createdAt: "2021-09-12T18:34:32.410Z",
            updatedAt: "2021-09-12T18:39:49.489Z",
            __v: 0,
            id: "613e48386b8d2300155e9d62",
          },
          id: "613e49756b8d2300155e9d64",
        },
        {
          __component: "post.paragraph",
          _id: "613e49756b8d2300155e9d65",
          text: "¿Te ha pasado que has publicado algo en tus redes sociales y no tienes un buen engagement?. Quizá has pasado bastante tiempo pensando en el contenido, pero cuando los publicas no consigues ni siquiera un like. ¿Qué está pasando? ¿Como puedes hacer para que tus contenidos atraigan a tu público?\n\nPuede que se te haya olvidado un factor importantísimo a la hora de planear tu estrategia de redes sociales: tener en cuenta los mejores horarios para publicar. ¿No lo habías pensado? Pues bien, a continuación, te vamos a contar como puedes conocer el mejor momento para postear en redes sociales.\n\nCuando posteas ignorando los horarios en que tus seguidores están activos en redes estas malgastando esfuerzos. Aunque tus contenidos sean los mejores. Si los publicas cuando no hay nadie viendo se esfumarán y pasarán desapercibidos. \n\nEso sí, ten en cuenta que no existe una “mejor hora” como tal, ya que el horario va a depender de múltiples factores. \n\n1. La red social en la que publicas: \n\n    No es lo mismo publicar para Twitter que para Instagram. Son redes sociales totalmente diferentes y por ende, tendrán sus propias frecuencias de publicación y esto es algo muy importante a   tener en cuenta. \n\n2.\tTu público objetivo:\n\n    Es fundamental conocer a las personas a las que nos dirigimos. Pero no solo conocer cuando están más activos en redes sociales, sino que también es muy importante saber el tipo de contenido que consumen. Para esto viene bien las herramientas de analítica y medición.\n\n3.\tEl sector de tu negocio:\n\n    El mejor momento para publicar no es el mismo para un restaurante que para una discoteca. Los momentos de actividad cambian y es algo que también hay que considerar.\n\nEntonces ¿Cómo puedes saber cuál es la mejor hora para publicar? \n\nPara ello puedes dejarte llevar por lo que indican diversos estudios, o bien puedes descubrir por ti mismo el momento optimo en que tus seguidores están mas activos y así optimizar tus contenidos.\n\nSi decides optar por la primera opción aquí te dejamos las mejores horas para publicar en redes sociales de acuerdo a los estudios.\n\n### to do\n\nSi quieres descubrir por ti mismo los horarios de actividad de tus seguidores, acá te mostramos algunas herramientas que te ayudaran a saber el mejor horario para publicar.  \n\n### to do\n\n",
          __v: 0,
          id: "613e49756b8d2300155e9d65",
        },
      ],
      createdAt: "2021-09-12T18:39:49.433Z",
      updatedAt: "2021-09-12T18:42:16.934Z",
      __v: 1,
      id: "613e49756b8d2300155e9d63",
    },
    {
      _id: "613e49756b8d2300155e9d63",
      title: "¿Cuáles son las mejores horas para publicar en redes?",
      slug: "cuales-son-las-mejores-horas-para-publicar-en-redes",
      description:
        "Cuando posteas ignorando los horarios en que tus seguidores están activos en redes estas malgastando esfuerzos. Aunque tus contenidos sean los mejores. Si los publicas cuando no hay nadie viendo se esfumarán y pasarán desapercibidos. ",
      published_at: "2021-09-12T18:42:16.864Z",
      postData: [
        {
          __component: "post.image",
          _id: "613e49756b8d2300155e9d64",
          imageDescription: "Redes sociales. Fuente: Pexels",
          __v: 0,
          image: {
            _id: "613e48386b8d2300155e9d62",
            name: "SocialNetworks.webp",
            alternativeText: "",
            caption: "",
            hash: "Social_Networks_943d5041ae",
            ext: ".webp",
            mime: "image/webp",
            size: 41.53,
            width: 1920,
            height: 1080,
            url: "https://infutblog.s3.us-east-2.amazonaws.com/Social_Networks_943d5041ae.webp",
            formats: {
              thumbnail: {
                name: "thumbnail_SocialNetworks.webp",
                hash: "thumbnail_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 245,
                height: 138,
                size: 3.92,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/thumbnail_Social_Networks_943d5041ae.webp",
              },
              large: {
                name: "large_SocialNetworks.webp",
                hash: "large_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 1000,
                height: 563,
                size: 21.1,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/large_Social_Networks_943d5041ae.webp",
              },
              medium: {
                name: "medium_SocialNetworks.webp",
                hash: "medium_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 750,
                height: 422,
                size: 15.42,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/medium_Social_Networks_943d5041ae.webp",
              },
              small: {
                name: "small_SocialNetworks.webp",
                hash: "small_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 500,
                height: 281,
                size: 9.56,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/small_Social_Networks_943d5041ae.webp",
              },
            },
            provider: "aws-s3",
            related: ["613e49756b8d2300155e9d64"],
            createdAt: "2021-09-12T18:34:32.410Z",
            updatedAt: "2021-09-12T18:39:49.489Z",
            __v: 0,
            id: "613e48386b8d2300155e9d62",
          },
          id: "613e49756b8d2300155e9d64",
        },
        {
          __component: "post.paragraph",
          _id: "613e49756b8d2300155e9d65",
          text: "¿Te ha pasado que has publicado algo en tus redes sociales y no tienes un buen engagement?. Quizá has pasado bastante tiempo pensando en el contenido, pero cuando los publicas no consigues ni siquiera un like. ¿Qué está pasando? ¿Como puedes hacer para que tus contenidos atraigan a tu público?\n\nPuede que se te haya olvidado un factor importantísimo a la hora de planear tu estrategia de redes sociales: tener en cuenta los mejores horarios para publicar. ¿No lo habías pensado? Pues bien, a continuación, te vamos a contar como puedes conocer el mejor momento para postear en redes sociales.\n\nCuando posteas ignorando los horarios en que tus seguidores están activos en redes estas malgastando esfuerzos. Aunque tus contenidos sean los mejores. Si los publicas cuando no hay nadie viendo se esfumarán y pasarán desapercibidos. \n\nEso sí, ten en cuenta que no existe una “mejor hora” como tal, ya que el horario va a depender de múltiples factores. \n\n1. La red social en la que publicas: \n\n    No es lo mismo publicar para Twitter que para Instagram. Son redes sociales totalmente diferentes y por ende, tendrán sus propias frecuencias de publicación y esto es algo muy importante a   tener en cuenta. \n\n2.\tTu público objetivo:\n\n    Es fundamental conocer a las personas a las que nos dirigimos. Pero no solo conocer cuando están más activos en redes sociales, sino que también es muy importante saber el tipo de contenido que consumen. Para esto viene bien las herramientas de analítica y medición.\n\n3.\tEl sector de tu negocio:\n\n    El mejor momento para publicar no es el mismo para un restaurante que para una discoteca. Los momentos de actividad cambian y es algo que también hay que considerar.\n\nEntonces ¿Cómo puedes saber cuál es la mejor hora para publicar? \n\nPara ello puedes dejarte llevar por lo que indican diversos estudios, o bien puedes descubrir por ti mismo el momento optimo en que tus seguidores están mas activos y así optimizar tus contenidos.\n\nSi decides optar por la primera opción aquí te dejamos las mejores horas para publicar en redes sociales de acuerdo a los estudios.\n\n### to do\n\nSi quieres descubrir por ti mismo los horarios de actividad de tus seguidores, acá te mostramos algunas herramientas que te ayudaran a saber el mejor horario para publicar.  \n\n### to do\n\n",
          __v: 0,
          id: "613e49756b8d2300155e9d65",
        },
      ],
      createdAt: "2021-09-12T18:39:49.433Z",
      updatedAt: "2021-09-12T18:42:16.934Z",
      __v: 1,
      id: "613e49756b8d2300155e9d63",
    },
    {
      _id: "613e49756b8d2300155e9d63",
      title: "¿Cuáles son las mejores horas para publicar en redes?",
      slug: "cuales-son-las-mejores-horas-para-publicar-en-redes",
      description:
        "Cuando posteas ignorando los horarios en que tus seguidores están activos en redes estas malgastando esfuerzos. Aunque tus contenidos sean los mejores. Si los publicas cuando no hay nadie viendo se esfumarán y pasarán desapercibidos. ",
      published_at: "2021-09-12T18:42:16.864Z",
      postData: [
        {
          __component: "post.image",
          _id: "613e49756b8d2300155e9d64",
          imageDescription: "Redes sociales. Fuente: Pexels",
          __v: 0,
          image: {
            _id: "613e48386b8d2300155e9d62",
            name: "SocialNetworks.webp",
            alternativeText: "",
            caption: "",
            hash: "Social_Networks_943d5041ae",
            ext: ".webp",
            mime: "image/webp",
            size: 41.53,
            width: 1920,
            height: 1080,
            url: "https://infutblog.s3.us-east-2.amazonaws.com/Social_Networks_943d5041ae.webp",
            formats: {
              thumbnail: {
                name: "thumbnail_SocialNetworks.webp",
                hash: "thumbnail_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 245,
                height: 138,
                size: 3.92,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/thumbnail_Social_Networks_943d5041ae.webp",
              },
              large: {
                name: "large_SocialNetworks.webp",
                hash: "large_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 1000,
                height: 563,
                size: 21.1,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/large_Social_Networks_943d5041ae.webp",
              },
              medium: {
                name: "medium_SocialNetworks.webp",
                hash: "medium_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 750,
                height: 422,
                size: 15.42,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/medium_Social_Networks_943d5041ae.webp",
              },
              small: {
                name: "small_SocialNetworks.webp",
                hash: "small_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 500,
                height: 281,
                size: 9.56,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/small_Social_Networks_943d5041ae.webp",
              },
            },
            provider: "aws-s3",
            related: ["613e49756b8d2300155e9d64"],
            createdAt: "2021-09-12T18:34:32.410Z",
            updatedAt: "2021-09-12T18:39:49.489Z",
            __v: 0,
            id: "613e48386b8d2300155e9d62",
          },
          id: "613e49756b8d2300155e9d64",
        },
        {
          __component: "post.paragraph",
          _id: "613e49756b8d2300155e9d65",
          text: "¿Te ha pasado que has publicado algo en tus redes sociales y no tienes un buen engagement?. Quizá has pasado bastante tiempo pensando en el contenido, pero cuando los publicas no consigues ni siquiera un like. ¿Qué está pasando? ¿Como puedes hacer para que tus contenidos atraigan a tu público?\n\nPuede que se te haya olvidado un factor importantísimo a la hora de planear tu estrategia de redes sociales: tener en cuenta los mejores horarios para publicar. ¿No lo habías pensado? Pues bien, a continuación, te vamos a contar como puedes conocer el mejor momento para postear en redes sociales.\n\nCuando posteas ignorando los horarios en que tus seguidores están activos en redes estas malgastando esfuerzos. Aunque tus contenidos sean los mejores. Si los publicas cuando no hay nadie viendo se esfumarán y pasarán desapercibidos. \n\nEso sí, ten en cuenta que no existe una “mejor hora” como tal, ya que el horario va a depender de múltiples factores. \n\n1. La red social en la que publicas: \n\n    No es lo mismo publicar para Twitter que para Instagram. Son redes sociales totalmente diferentes y por ende, tendrán sus propias frecuencias de publicación y esto es algo muy importante a   tener en cuenta. \n\n2.\tTu público objetivo:\n\n    Es fundamental conocer a las personas a las que nos dirigimos. Pero no solo conocer cuando están más activos en redes sociales, sino que también es muy importante saber el tipo de contenido que consumen. Para esto viene bien las herramientas de analítica y medición.\n\n3.\tEl sector de tu negocio:\n\n    El mejor momento para publicar no es el mismo para un restaurante que para una discoteca. Los momentos de actividad cambian y es algo que también hay que considerar.\n\nEntonces ¿Cómo puedes saber cuál es la mejor hora para publicar? \n\nPara ello puedes dejarte llevar por lo que indican diversos estudios, o bien puedes descubrir por ti mismo el momento optimo en que tus seguidores están mas activos y así optimizar tus contenidos.\n\nSi decides optar por la primera opción aquí te dejamos las mejores horas para publicar en redes sociales de acuerdo a los estudios.\n\n### to do\n\nSi quieres descubrir por ti mismo los horarios de actividad de tus seguidores, acá te mostramos algunas herramientas que te ayudaran a saber el mejor horario para publicar.  \n\n### to do\n\n",
          __v: 0,
          id: "613e49756b8d2300155e9d65",
        },
      ],
      createdAt: "2021-09-12T18:39:49.433Z",
      updatedAt: "2021-09-12T18:42:16.934Z",
      __v: 1,
      id: "613e49756b8d2300155e9d63",
    },
    {
      _id: "613e49756b8d2300155e9d63",
      title: "¿Cuáles son las mejores horas para publicar en redes?",
      slug: "cuales-son-las-mejores-horas-para-publicar-en-redes",
      description:
        "Cuando posteas ignorando los horarios en que tus seguidores están activos en redes estas malgastando esfuerzos. Aunque tus contenidos sean los mejores. Si los publicas cuando no hay nadie viendo se esfumarán y pasarán desapercibidos. ",
      published_at: "2021-09-12T18:42:16.864Z",
      postData: [
        {
          __component: "post.image",
          _id: "613e49756b8d2300155e9d64",
          imageDescription: "Redes sociales. Fuente: Pexels",
          __v: 0,
          image: {
            _id: "613e48386b8d2300155e9d62",
            name: "SocialNetworks.webp",
            alternativeText: "",
            caption: "",
            hash: "Social_Networks_943d5041ae",
            ext: ".webp",
            mime: "image/webp",
            size: 41.53,
            width: 1920,
            height: 1080,
            url: "https://infutblog.s3.us-east-2.amazonaws.com/Social_Networks_943d5041ae.webp",
            formats: {
              thumbnail: {
                name: "thumbnail_SocialNetworks.webp",
                hash: "thumbnail_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 245,
                height: 138,
                size: 3.92,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/thumbnail_Social_Networks_943d5041ae.webp",
              },
              large: {
                name: "large_SocialNetworks.webp",
                hash: "large_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 1000,
                height: 563,
                size: 21.1,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/large_Social_Networks_943d5041ae.webp",
              },
              medium: {
                name: "medium_SocialNetworks.webp",
                hash: "medium_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 750,
                height: 422,
                size: 15.42,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/medium_Social_Networks_943d5041ae.webp",
              },
              small: {
                name: "small_SocialNetworks.webp",
                hash: "small_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 500,
                height: 281,
                size: 9.56,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/small_Social_Networks_943d5041ae.webp",
              },
            },
            provider: "aws-s3",
            related: ["613e49756b8d2300155e9d64"],
            createdAt: "2021-09-12T18:34:32.410Z",
            updatedAt: "2021-09-12T18:39:49.489Z",
            __v: 0,
            id: "613e48386b8d2300155e9d62",
          },
          id: "613e49756b8d2300155e9d64",
        },
        {
          __component: "post.paragraph",
          _id: "613e49756b8d2300155e9d65",
          text: "¿Te ha pasado que has publicado algo en tus redes sociales y no tienes un buen engagement?. Quizá has pasado bastante tiempo pensando en el contenido, pero cuando los publicas no consigues ni siquiera un like. ¿Qué está pasando? ¿Como puedes hacer para que tus contenidos atraigan a tu público?\n\nPuede que se te haya olvidado un factor importantísimo a la hora de planear tu estrategia de redes sociales: tener en cuenta los mejores horarios para publicar. ¿No lo habías pensado? Pues bien, a continuación, te vamos a contar como puedes conocer el mejor momento para postear en redes sociales.\n\nCuando posteas ignorando los horarios en que tus seguidores están activos en redes estas malgastando esfuerzos. Aunque tus contenidos sean los mejores. Si los publicas cuando no hay nadie viendo se esfumarán y pasarán desapercibidos. \n\nEso sí, ten en cuenta que no existe una “mejor hora” como tal, ya que el horario va a depender de múltiples factores. \n\n1. La red social en la que publicas: \n\n    No es lo mismo publicar para Twitter que para Instagram. Son redes sociales totalmente diferentes y por ende, tendrán sus propias frecuencias de publicación y esto es algo muy importante a   tener en cuenta. \n\n2.\tTu público objetivo:\n\n    Es fundamental conocer a las personas a las que nos dirigimos. Pero no solo conocer cuando están más activos en redes sociales, sino que también es muy importante saber el tipo de contenido que consumen. Para esto viene bien las herramientas de analítica y medición.\n\n3.\tEl sector de tu negocio:\n\n    El mejor momento para publicar no es el mismo para un restaurante que para una discoteca. Los momentos de actividad cambian y es algo que también hay que considerar.\n\nEntonces ¿Cómo puedes saber cuál es la mejor hora para publicar? \n\nPara ello puedes dejarte llevar por lo que indican diversos estudios, o bien puedes descubrir por ti mismo el momento optimo en que tus seguidores están mas activos y así optimizar tus contenidos.\n\nSi decides optar por la primera opción aquí te dejamos las mejores horas para publicar en redes sociales de acuerdo a los estudios.\n\n### to do\n\nSi quieres descubrir por ti mismo los horarios de actividad de tus seguidores, acá te mostramos algunas herramientas que te ayudaran a saber el mejor horario para publicar.  \n\n### to do\n\n",
          __v: 0,
          id: "613e49756b8d2300155e9d65",
        },
      ],
      createdAt: "2021-09-12T18:39:49.433Z",
      updatedAt: "2021-09-12T18:42:16.934Z",
      __v: 1,
      id: "613e49756b8d2300155e9d63",
    },
    {
      _id: "613e49756b8d2300155e9d63",
      title: "¿Cuáles son las mejores horas para publicar en redes?",
      slug: "cuales-son-las-mejores-horas-para-publicar-en-redes",
      description:
        "Cuando posteas ignorando los horarios en que tus seguidores están activos en redes estas malgastando esfuerzos. Aunque tus contenidos sean los mejores. Si los publicas cuando no hay nadie viendo se esfumarán y pasarán desapercibidos. ",
      published_at: "2021-09-12T18:42:16.864Z",
      postData: [
        {
          __component: "post.image",
          _id: "613e49756b8d2300155e9d64",
          imageDescription: "Redes sociales. Fuente: Pexels",
          __v: 0,
          image: {
            _id: "613e48386b8d2300155e9d62",
            name: "SocialNetworks.webp",
            alternativeText: "",
            caption: "",
            hash: "Social_Networks_943d5041ae",
            ext: ".webp",
            mime: "image/webp",
            size: 41.53,
            width: 1920,
            height: 1080,
            url: "https://infutblog.s3.us-east-2.amazonaws.com/Social_Networks_943d5041ae.webp",
            formats: {
              thumbnail: {
                name: "thumbnail_SocialNetworks.webp",
                hash: "thumbnail_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 245,
                height: 138,
                size: 3.92,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/thumbnail_Social_Networks_943d5041ae.webp",
              },
              large: {
                name: "large_SocialNetworks.webp",
                hash: "large_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 1000,
                height: 563,
                size: 21.1,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/large_Social_Networks_943d5041ae.webp",
              },
              medium: {
                name: "medium_SocialNetworks.webp",
                hash: "medium_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 750,
                height: 422,
                size: 15.42,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/medium_Social_Networks_943d5041ae.webp",
              },
              small: {
                name: "small_SocialNetworks.webp",
                hash: "small_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 500,
                height: 281,
                size: 9.56,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/small_Social_Networks_943d5041ae.webp",
              },
            },
            provider: "aws-s3",
            related: ["613e49756b8d2300155e9d64"],
            createdAt: "2021-09-12T18:34:32.410Z",
            updatedAt: "2021-09-12T18:39:49.489Z",
            __v: 0,
            id: "613e48386b8d2300155e9d62",
          },
          id: "613e49756b8d2300155e9d64",
        },
        {
          __component: "post.paragraph",
          _id: "613e49756b8d2300155e9d65",
          text: "¿Te ha pasado que has publicado algo en tus redes sociales y no tienes un buen engagement?. Quizá has pasado bastante tiempo pensando en el contenido, pero cuando los publicas no consigues ni siquiera un like. ¿Qué está pasando? ¿Como puedes hacer para que tus contenidos atraigan a tu público?\n\nPuede que se te haya olvidado un factor importantísimo a la hora de planear tu estrategia de redes sociales: tener en cuenta los mejores horarios para publicar. ¿No lo habías pensado? Pues bien, a continuación, te vamos a contar como puedes conocer el mejor momento para postear en redes sociales.\n\nCuando posteas ignorando los horarios en que tus seguidores están activos en redes estas malgastando esfuerzos. Aunque tus contenidos sean los mejores. Si los publicas cuando no hay nadie viendo se esfumarán y pasarán desapercibidos. \n\nEso sí, ten en cuenta que no existe una “mejor hora” como tal, ya que el horario va a depender de múltiples factores. \n\n1. La red social en la que publicas: \n\n    No es lo mismo publicar para Twitter que para Instagram. Son redes sociales totalmente diferentes y por ende, tendrán sus propias frecuencias de publicación y esto es algo muy importante a   tener en cuenta. \n\n2.\tTu público objetivo:\n\n    Es fundamental conocer a las personas a las que nos dirigimos. Pero no solo conocer cuando están más activos en redes sociales, sino que también es muy importante saber el tipo de contenido que consumen. Para esto viene bien las herramientas de analítica y medición.\n\n3.\tEl sector de tu negocio:\n\n    El mejor momento para publicar no es el mismo para un restaurante que para una discoteca. Los momentos de actividad cambian y es algo que también hay que considerar.\n\nEntonces ¿Cómo puedes saber cuál es la mejor hora para publicar? \n\nPara ello puedes dejarte llevar por lo que indican diversos estudios, o bien puedes descubrir por ti mismo el momento optimo en que tus seguidores están mas activos y así optimizar tus contenidos.\n\nSi decides optar por la primera opción aquí te dejamos las mejores horas para publicar en redes sociales de acuerdo a los estudios.\n\n### to do\n\nSi quieres descubrir por ti mismo los horarios de actividad de tus seguidores, acá te mostramos algunas herramientas que te ayudaran a saber el mejor horario para publicar.  \n\n### to do\n\n",
          __v: 0,
          id: "613e49756b8d2300155e9d65",
        },
      ],
      createdAt: "2021-09-12T18:39:49.433Z",
      updatedAt: "2021-09-12T18:42:16.934Z",
      __v: 1,
      id: "613e49756b8d2300155e9d63",
    },
    {
      _id: "613e49756b8d2300155e9d63",
      title: "¿Cuáles son las mejores horas para publicar en redes?",
      slug: "cuales-son-las-mejores-horas-para-publicar-en-redes",
      description:
        "Cuando posteas ignorando los horarios en que tus seguidores están activos en redes estas malgastando esfuerzos. Aunque tus contenidos sean los mejores. Si los publicas cuando no hay nadie viendo se esfumarán y pasarán desapercibidos. ",
      published_at: "2021-09-12T18:42:16.864Z",
      postData: [
        {
          __component: "post.image",
          _id: "613e49756b8d2300155e9d64",
          imageDescription: "Redes sociales. Fuente: Pexels",
          __v: 0,
          image: {
            _id: "613e48386b8d2300155e9d62",
            name: "SocialNetworks.webp",
            alternativeText: "",
            caption: "",
            hash: "Social_Networks_943d5041ae",
            ext: ".webp",
            mime: "image/webp",
            size: 41.53,
            width: 1920,
            height: 1080,
            url: "https://infutblog.s3.us-east-2.amazonaws.com/Social_Networks_943d5041ae.webp",
            formats: {
              thumbnail: {
                name: "thumbnail_SocialNetworks.webp",
                hash: "thumbnail_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 245,
                height: 138,
                size: 3.92,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/thumbnail_Social_Networks_943d5041ae.webp",
              },
              large: {
                name: "large_SocialNetworks.webp",
                hash: "large_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 1000,
                height: 563,
                size: 21.1,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/large_Social_Networks_943d5041ae.webp",
              },
              medium: {
                name: "medium_SocialNetworks.webp",
                hash: "medium_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 750,
                height: 422,
                size: 15.42,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/medium_Social_Networks_943d5041ae.webp",
              },
              small: {
                name: "small_SocialNetworks.webp",
                hash: "small_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 500,
                height: 281,
                size: 9.56,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/small_Social_Networks_943d5041ae.webp",
              },
            },
            provider: "aws-s3",
            related: ["613e49756b8d2300155e9d64"],
            createdAt: "2021-09-12T18:34:32.410Z",
            updatedAt: "2021-09-12T18:39:49.489Z",
            __v: 0,
            id: "613e48386b8d2300155e9d62",
          },
          id: "613e49756b8d2300155e9d64",
        },
        {
          __component: "post.paragraph",
          _id: "613e49756b8d2300155e9d65",
          text: "¿Te ha pasado que has publicado algo en tus redes sociales y no tienes un buen engagement?. Quizá has pasado bastante tiempo pensando en el contenido, pero cuando los publicas no consigues ni siquiera un like. ¿Qué está pasando? ¿Como puedes hacer para que tus contenidos atraigan a tu público?\n\nPuede que se te haya olvidado un factor importantísimo a la hora de planear tu estrategia de redes sociales: tener en cuenta los mejores horarios para publicar. ¿No lo habías pensado? Pues bien, a continuación, te vamos a contar como puedes conocer el mejor momento para postear en redes sociales.\n\nCuando posteas ignorando los horarios en que tus seguidores están activos en redes estas malgastando esfuerzos. Aunque tus contenidos sean los mejores. Si los publicas cuando no hay nadie viendo se esfumarán y pasarán desapercibidos. \n\nEso sí, ten en cuenta que no existe una “mejor hora” como tal, ya que el horario va a depender de múltiples factores. \n\n1. La red social en la que publicas: \n\n    No es lo mismo publicar para Twitter que para Instagram. Son redes sociales totalmente diferentes y por ende, tendrán sus propias frecuencias de publicación y esto es algo muy importante a   tener en cuenta. \n\n2.\tTu público objetivo:\n\n    Es fundamental conocer a las personas a las que nos dirigimos. Pero no solo conocer cuando están más activos en redes sociales, sino que también es muy importante saber el tipo de contenido que consumen. Para esto viene bien las herramientas de analítica y medición.\n\n3.\tEl sector de tu negocio:\n\n    El mejor momento para publicar no es el mismo para un restaurante que para una discoteca. Los momentos de actividad cambian y es algo que también hay que considerar.\n\nEntonces ¿Cómo puedes saber cuál es la mejor hora para publicar? \n\nPara ello puedes dejarte llevar por lo que indican diversos estudios, o bien puedes descubrir por ti mismo el momento optimo en que tus seguidores están mas activos y así optimizar tus contenidos.\n\nSi decides optar por la primera opción aquí te dejamos las mejores horas para publicar en redes sociales de acuerdo a los estudios.\n\n### to do\n\nSi quieres descubrir por ti mismo los horarios de actividad de tus seguidores, acá te mostramos algunas herramientas que te ayudaran a saber el mejor horario para publicar.  \n\n### to do\n\n",
          __v: 0,
          id: "613e49756b8d2300155e9d65",
        },
      ],
      createdAt: "2021-09-12T18:39:49.433Z",
      updatedAt: "2021-09-12T18:42:16.934Z",
      __v: 1,
      id: "613e49756b8d2300155e9d63",
    },
    {
      _id: "613e49756b8d2300155e9d63",
      title: "¿Cuáles son las mejores horas para publicar en redes?",
      slug: "cuales-son-las-mejores-horas-para-publicar-en-redes",
      description:
        "Cuando posteas ignorando los horarios en que tus seguidores están activos en redes estas malgastando esfuerzos. Aunque tus contenidos sean los mejores. Si los publicas cuando no hay nadie viendo se esfumarán y pasarán desapercibidos. ",
      published_at: "2021-09-12T18:42:16.864Z",
      postData: [
        {
          __component: "post.image",
          _id: "613e49756b8d2300155e9d64",
          imageDescription: "Redes sociales. Fuente: Pexels",
          __v: 0,
          image: {
            _id: "613e48386b8d2300155e9d62",
            name: "SocialNetworks.webp",
            alternativeText: "",
            caption: "",
            hash: "Social_Networks_943d5041ae",
            ext: ".webp",
            mime: "image/webp",
            size: 41.53,
            width: 1920,
            height: 1080,
            url: "https://infutblog.s3.us-east-2.amazonaws.com/Social_Networks_943d5041ae.webp",
            formats: {
              thumbnail: {
                name: "thumbnail_SocialNetworks.webp",
                hash: "thumbnail_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 245,
                height: 138,
                size: 3.92,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/thumbnail_Social_Networks_943d5041ae.webp",
              },
              large: {
                name: "large_SocialNetworks.webp",
                hash: "large_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 1000,
                height: 563,
                size: 21.1,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/large_Social_Networks_943d5041ae.webp",
              },
              medium: {
                name: "medium_SocialNetworks.webp",
                hash: "medium_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 750,
                height: 422,
                size: 15.42,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/medium_Social_Networks_943d5041ae.webp",
              },
              small: {
                name: "small_SocialNetworks.webp",
                hash: "small_Social_Networks_943d5041ae",
                ext: ".webp",
                mime: "image/webp",
                width: 500,
                height: 281,
                size: 9.56,
                path: null,
                url: "https://infutblog.s3.us-east-2.amazonaws.com/small_Social_Networks_943d5041ae.webp",
              },
            },
            provider: "aws-s3",
            related: ["613e49756b8d2300155e9d64"],
            createdAt: "2021-09-12T18:34:32.410Z",
            updatedAt: "2021-09-12T18:39:49.489Z",
            __v: 0,
            id: "613e48386b8d2300155e9d62",
          },
          id: "613e49756b8d2300155e9d64",
        },
        {
          __component: "post.paragraph",
          _id: "613e49756b8d2300155e9d65",
          text: "¿Te ha pasado que has publicado algo en tus redes sociales y no tienes un buen engagement?. Quizá has pasado bastante tiempo pensando en el contenido, pero cuando los publicas no consigues ni siquiera un like. ¿Qué está pasando? ¿Como puedes hacer para que tus contenidos atraigan a tu público?\n\nPuede que se te haya olvidado un factor importantísimo a la hora de planear tu estrategia de redes sociales: tener en cuenta los mejores horarios para publicar. ¿No lo habías pensado? Pues bien, a continuación, te vamos a contar como puedes conocer el mejor momento para postear en redes sociales.\n\nCuando posteas ignorando los horarios en que tus seguidores están activos en redes estas malgastando esfuerzos. Aunque tus contenidos sean los mejores. Si los publicas cuando no hay nadie viendo se esfumarán y pasarán desapercibidos. \n\nEso sí, ten en cuenta que no existe una “mejor hora” como tal, ya que el horario va a depender de múltiples factores. \n\n1. La red social en la que publicas: \n\n    No es lo mismo publicar para Twitter que para Instagram. Son redes sociales totalmente diferentes y por ende, tendrán sus propias frecuencias de publicación y esto es algo muy importante a   tener en cuenta. \n\n2.\tTu público objetivo:\n\n    Es fundamental conocer a las personas a las que nos dirigimos. Pero no solo conocer cuando están más activos en redes sociales, sino que también es muy importante saber el tipo de contenido que consumen. Para esto viene bien las herramientas de analítica y medición.\n\n3.\tEl sector de tu negocio:\n\n    El mejor momento para publicar no es el mismo para un restaurante que para una discoteca. Los momentos de actividad cambian y es algo que también hay que considerar.\n\nEntonces ¿Cómo puedes saber cuál es la mejor hora para publicar? \n\nPara ello puedes dejarte llevar por lo que indican diversos estudios, o bien puedes descubrir por ti mismo el momento optimo en que tus seguidores están mas activos y así optimizar tus contenidos.\n\nSi decides optar por la primera opción aquí te dejamos las mejores horas para publicar en redes sociales de acuerdo a los estudios.\n\n### to do\n\nSi quieres descubrir por ti mismo los horarios de actividad de tus seguidores, acá te mostramos algunas herramientas que te ayudaran a saber el mejor horario para publicar.  \n\n### to do\n\n",
          __v: 0,
          id: "613e49756b8d2300155e9d65",
        },
      ],
      createdAt: "2021-09-12T18:39:49.433Z",
      updatedAt: "2021-09-12T18:42:16.934Z",
      __v: 1,
      id: "613e49756b8d2300155e9d63",
    },
  ];
  return (
    <>
      <Navbar bg />
      <Row col={4}>
        {demopost.map((post) => (
          <PostCard post={post} key={`post_${post.id}`} />
        ))}
      </Row>
    </>
  );
};

export default blog;
